### ISSUE TITLE
Use package source code in local

### ISSUE THREAD

**Issue by i7eo** [spautz/changesets-changelog-format#22]
I see you set "source" field in  changsets-format-with-issue-links package.json. Are you using that field to debug changsets-format-with-issue-links source code in basic-demo?

**Comment by spautz** [comment]
The main reason is that `source` can give a better dev experience in some IDEs. In WebStorm you can "Go to Implementation" and it'll take you to the original file in src instead of bringing you to the typings, for example. (That's less useful in changsets-format-with-issue-links than in a package you import normally, though.) In theory it might be useful to some consumers' build systems as well, although I've never needed that.

I've never heard of using it to debug. Is there a technique there that might be useful?

**Comment by i7eo** [comment]
Thank you, through your description, I understand the meaning of the `source` field. My question is how to invoke package source code in monorepo project where you executed `pnpm run build:main` to make sure the compiled code is called in `basic-demo`

**Comment by i7eo** [comment]
> The main reason is that `source` can give a better dev experience in some IDEs. In WebStorm you can "Go to Implementation" and it'll take you to the original file in src instead of bringing you to the typings, for example. (That's less useful in changsets-format-with-issue-links than in a package you import normally, though.) In theory it might be useful to some consumers' build systems as well, although I've never needed that.
> 
> I've never heard of using it to debug. Is there a technique there that might be useful?

Thank you, through your description, I understand the meaning of the source field. My question is how to invoke package source code in monorepo project where you executed pnpm run build:main to make sure the compiled code is called in basic-demo

**Comment by spautz** [comment]
I'm sorry, I don't quite understand your question. Here is an overall description of how things are set up: does this information help?

* The `build:main` script runs runs automatically when setting up the pnpm workspace (with the `prepare` lifecycle script, [here](https://github.com/spautz/changesets-changelog-format/blob/main/packages/changesets-format-with-issue-links/package.json#L52)). So, running `pnpm install` for local development will build the packages.
* Once that build script has run, other projects in the [pnpm workspace](https://pnpm.io/workspaces) can import and use it. The basic-demo uses `workspace:*` to link the two projects together ([here](https://github.com/spautz/changesets-changelog-format/blob/main/demos/basic-demo/package.json#L26))
* With this setup, when `pnpm install` is run for local development, the code for changesets-format-with-issue-links gets compiled automatically, and then the pnpm workspace installs the package in the basic-demo app -- so it works the same as if the package was installed from npm, except it uses the local code. (So it is useful for debugging, and also useful for testing to make sure the package works correctly.)

Is this what you are asking about?

**Comment by i7eo** [comment]
Thx
